spring.application.name=bedmaster-routing-engine

spring.datasource.url=jdbc:mysql://localhost:3306/bedmasterDB
spring.datasource.username=root
spring.datasource.password=la@vanya@1124

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 8081